name: Update Issues Badge

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write
  issues: read

jobs:
  update-badge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fetch issue count
        run: |
          # Print the API response for debugging
          curl -s -H "Authorization: token ${{ github.token }}" \
            "https://api.github.com/search/issues?q=repo:KittyCAD/modeling-app+type:issue+author:jgomez720"
          
          COUNT=$(curl -s -H "Authorization: token ${{ github.token }}" \
            "https://api.github.com/search/issues?q=repo:KittyCAD/modeling-app+type:issue+author:jgomez720" \
            | jq '.total_count')

          BADGE="![Modeling App Issues](https://img.shields.io/badge/Issues%20Created-$COUNT-blue)"

          # Ensure README.md exists
          if [ ! -f README.md ]; then
            echo "# My GitHub Profile" > README.md
          fi
          
          # Update the badge in README.md
          if grep -q "!\[Modeling App Issues\]" README.md; then
            sed -i "s|!\[Modeling App Issues\].*|$BADGE|" README.md
          else
            echo -e "\n$BADGE" >> README.md
          fi
          
      - name: Ensure issue_badge.md exists
        run: |
          touch issue_badge.md
          echo "Issue badge file verified."

      - name: Update and Push 
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add issue_badge.md
          git commit -m "Updated issue count badge" || echo "No changes to commit"
          git push
